### ISSUE TITLE
Alumni — Refaire from scratch

### ISSUE THREAD

**Issue by Papillard** [lewagon/www#26]
Inspi: http://alumni.lewagon.org/batches/11 ou bannière slack pr mettre en avant une story

TODO
- replacement des avatars des élèves en mode cool
- Featured projects:

```yaml
# config/site.yml
home:
  alumni:
    - 1 (ou slug)
    - 3
    - 5
  home:
    - slug1
    - slug2
```

API:

https://alumni.lewagon.org/api/v1/projects.json?slug=:slug1,:slug2,:slug3
=> Renvoie uniquement les projects slugés.
Du coup "Featured" saute en back sur l'API. Et le ìndexfait un `where(slug: params[:slug])`
